/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoadsRouteImport } from './routes/_authenticated/roads'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSimulateRouteImport } from './routes/_authenticated/simulate'
import { Route as AuthenticatedSimulationsRouteImport } from './routes/_authenticated/simulations'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedRoadsIndexRouteImport } from './routes/_authenticated/roads.index'
import { Route as AuthenticatedRoadsIdRouteImport } from './routes/_authenticated/roads.$id'
import { Route as AuthenticatedRoadsNewRouteImport } from './routes/_authenticated/roads.new'
import { Route as AuthenticatedSimulationsIndexRouteImport } from './routes/_authenticated/simulations.index'
import { Route as AuthenticatedSimulationsIdRouteImport } from './routes/_authenticated/simulations.$id'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles.index'
import { Route as AuthenticatedVehiclesIdRouteImport } from './routes/_authenticated/vehicles.$id'
import { Route as AuthenticatedVehiclesNewRouteImport } from './routes/_authenticated/vehicles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadsRoute = AuthenticatedRoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulateRoute = AuthenticatedSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulationsRoute =
  AuthenticatedSimulationsRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoadsIndexRoute = AuthenticatedRoadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoadsRoute,
} as any)
const AuthenticatedRoadsIdRoute = AuthenticatedRoadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRoadsRoute,
} as any)
const AuthenticatedRoadsNewRoute = AuthenticatedRoadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoadsRoute,
} as any)
const AuthenticatedSimulationsIndexRoute =
  AuthenticatedSimulationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSimulationsRoute,
  } as any)
const AuthenticatedSimulationsIdRoute =
  AuthenticatedSimulationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSimulationsRoute,
  } as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVehiclesRoute,
  } as any)
const AuthenticatedVehiclesIdRoute = AuthenticatedVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVehiclesRoute,
} as any)
const AuthenticatedVehiclesNewRoute =
  AuthenticatedVehiclesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedVehiclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/roads': typeof AuthenticatedRoadsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
  '/simulations': typeof AuthenticatedSimulationsRouteWithChildren
  '/vehicles': typeof AuthenticatedVehiclesRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/roads/$id': typeof AuthenticatedRoadsIdRoute
  '/roads/new': typeof AuthenticatedRoadsNewRoute
  '/simulations/$id': typeof AuthenticatedSimulationsIdRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdRoute
  '/vehicles/new': typeof AuthenticatedVehiclesNewRoute
  '/roads/': typeof AuthenticatedRoadsIndexRoute
  '/simulations/': typeof AuthenticatedSimulationsIndexRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulate': typeof AuthenticatedSimulateRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/roads/$id': typeof AuthenticatedRoadsIdRoute
  '/roads/new': typeof AuthenticatedRoadsNewRoute
  '/simulations/$id': typeof AuthenticatedSimulationsIdRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdRoute
  '/vehicles/new': typeof AuthenticatedVehiclesNewRoute
  '/roads': typeof AuthenticatedRoadsIndexRoute
  '/simulations': typeof AuthenticatedSimulationsIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/roads': typeof AuthenticatedRoadsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/simulate': typeof AuthenticatedSimulateRoute
  '/_authenticated/simulations': typeof AuthenticatedSimulationsRouteWithChildren
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/roads/$id': typeof AuthenticatedRoadsIdRoute
  '/_authenticated/roads/new': typeof AuthenticatedRoadsNewRoute
  '/_authenticated/simulations/$id': typeof AuthenticatedSimulationsIdRoute
  '/_authenticated/vehicles/$id': typeof AuthenticatedVehiclesIdRoute
  '/_authenticated/vehicles/new': typeof AuthenticatedVehiclesNewRoute
  '/_authenticated/roads/': typeof AuthenticatedRoadsIndexRoute
  '/_authenticated/simulations/': typeof AuthenticatedSimulationsIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/roads'
    | '/settings'
    | '/simulate'
    | '/simulations'
    | '/vehicles'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/roads/$id'
    | '/roads/new'
    | '/simulations/$id'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/roads/'
    | '/simulations/'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/settings'
    | '/simulate'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/roads/$id'
    | '/roads/new'
    | '/simulations/$id'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/roads'
    | '/simulations'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/roads'
    | '/_authenticated/settings'
    | '/_authenticated/simulate'
    | '/_authenticated/simulations'
    | '/_authenticated/vehicles'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/roads/$id'
    | '/_authenticated/roads/new'
    | '/_authenticated/simulations/$id'
    | '/_authenticated/vehicles/$id'
    | '/_authenticated/vehicles/new'
    | '/_authenticated/roads/'
    | '/_authenticated/simulations/'
    | '/_authenticated/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roads': {
      id: '/_authenticated/roads'
      path: '/roads'
      fullPath: '/roads'
      preLoaderRoute: typeof AuthenticatedRoadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulate': {
      id: '/_authenticated/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof AuthenticatedSimulateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulations': {
      id: '/_authenticated/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof AuthenticatedSimulationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roads/': {
      id: '/_authenticated/roads/'
      path: '/'
      fullPath: '/roads/'
      preLoaderRoute: typeof AuthenticatedRoadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoadsRoute
    }
    '/_authenticated/roads/$id': {
      id: '/_authenticated/roads/$id'
      path: '/$id'
      fullPath: '/roads/$id'
      preLoaderRoute: typeof AuthenticatedRoadsIdRouteImport
      parentRoute: typeof AuthenticatedRoadsRoute
    }
    '/_authenticated/roads/new': {
      id: '/_authenticated/roads/new'
      path: '/new'
      fullPath: '/roads/new'
      preLoaderRoute: typeof AuthenticatedRoadsNewRouteImport
      parentRoute: typeof AuthenticatedRoadsRoute
    }
    '/_authenticated/simulations/': {
      id: '/_authenticated/simulations/'
      path: '/'
      fullPath: '/simulations/'
      preLoaderRoute: typeof AuthenticatedSimulationsIndexRouteImport
      parentRoute: typeof AuthenticatedSimulationsRoute
    }
    '/_authenticated/simulations/$id': {
      id: '/_authenticated/simulations/$id'
      path: '/$id'
      fullPath: '/simulations/$id'
      preLoaderRoute: typeof AuthenticatedSimulationsIdRouteImport
      parentRoute: typeof AuthenticatedSimulationsRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedVehiclesRoute
    }
    '/_authenticated/vehicles/$id': {
      id: '/_authenticated/vehicles/$id'
      path: '/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof AuthenticatedVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedVehiclesRoute
    }
    '/_authenticated/vehicles/new': {
      id: '/_authenticated/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof AuthenticatedVehiclesNewRouteImport
      parentRoute: typeof AuthenticatedVehiclesRoute
    }
  }
}

interface AuthenticatedRoadsRouteChildren {
  AuthenticatedRoadsIdRoute: typeof AuthenticatedRoadsIdRoute
  AuthenticatedRoadsNewRoute: typeof AuthenticatedRoadsNewRoute
  AuthenticatedRoadsIndexRoute: typeof AuthenticatedRoadsIndexRoute
}

const AuthenticatedRoadsRouteChildren: AuthenticatedRoadsRouteChildren = {
  AuthenticatedRoadsIdRoute: AuthenticatedRoadsIdRoute,
  AuthenticatedRoadsNewRoute: AuthenticatedRoadsNewRoute,
  AuthenticatedRoadsIndexRoute: AuthenticatedRoadsIndexRoute,
}

const AuthenticatedRoadsRouteWithChildren =
  AuthenticatedRoadsRoute._addFileChildren(AuthenticatedRoadsRouteChildren)

interface AuthenticatedSimulationsRouteChildren {
  AuthenticatedSimulationsIdRoute: typeof AuthenticatedSimulationsIdRoute
  AuthenticatedSimulationsIndexRoute: typeof AuthenticatedSimulationsIndexRoute
}

const AuthenticatedSimulationsRouteChildren: AuthenticatedSimulationsRouteChildren =
  {
    AuthenticatedSimulationsIdRoute: AuthenticatedSimulationsIdRoute,
    AuthenticatedSimulationsIndexRoute: AuthenticatedSimulationsIndexRoute,
  }

const AuthenticatedSimulationsRouteWithChildren =
  AuthenticatedSimulationsRoute._addFileChildren(
    AuthenticatedSimulationsRouteChildren,
  )

interface AuthenticatedVehiclesRouteChildren {
  AuthenticatedVehiclesIdRoute: typeof AuthenticatedVehiclesIdRoute
  AuthenticatedVehiclesNewRoute: typeof AuthenticatedVehiclesNewRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
}

const AuthenticatedVehiclesRouteChildren: AuthenticatedVehiclesRouteChildren = {
  AuthenticatedVehiclesIdRoute: AuthenticatedVehiclesIdRoute,
  AuthenticatedVehiclesNewRoute: AuthenticatedVehiclesNewRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
}

const AuthenticatedVehiclesRouteWithChildren =
  AuthenticatedVehiclesRoute._addFileChildren(
    AuthenticatedVehiclesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRoadsRoute: typeof AuthenticatedRoadsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulateRoute: typeof AuthenticatedSimulateRoute
  AuthenticatedSimulationsRoute: typeof AuthenticatedSimulationsRouteWithChildren
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRoadsRoute: AuthenticatedRoadsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulateRoute: AuthenticatedSimulateRoute,
  AuthenticatedSimulationsRoute: AuthenticatedSimulationsRouteWithChildren,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
